program NK;

uses
  Forms,
  DB,
  DBTables,
  UMenuP in 'UMenuP.pas' {fMenuP},
  UDM1 in 'UDM1.pas' {DM1: TDataModule},
  UGrupos in 'UGrupos.pas' {fGrupos},
  UFornecedores in 'UFornecedores.pas' {fFornecedores},
  UMaterial in 'UMaterial.pas' {fMaterial},
  UGrade in 'UGrade.pas' {fGrade},
  UOrdemCompra in 'UOrdemCompra.pas' {fOrdemCompra},
  UOrdemCompraCor in 'UOrdemCompraCor.pas' {fOrdemCompraCor},
  UEmpresa in 'UEmpresa.pas' {fEmpresa},
  UProduto in 'UProduto.pas' {fProduto},
  UMaterialGrade in 'UMaterialGrade.pas' {fMaterialGrade},
  URelMaterial in 'URelMaterial.pas' {fRelMaterial},
  UPrevMaterial in 'UPrevMaterial.pas' {fPrevMaterial},
  UVendedor in 'UVendedor.pas' {fVendedor},
  UPedido in 'UPedido.pas' {fPedido},
  UCliente in 'UCliente.pas' {fCliente},
  UPedidoGrade in 'UPedidoGrade.pas' {fPedidoGrade},
  UPedidoMat in 'UPedidoMat.pas' {fPedidoMat},
  UPedidoDesconto in 'UPedidoDesconto.pas' {fPedidoDesconto},
  URelPedido in 'URelPedido.pas' {fRelPedido},
  UPrevRelClientes in 'UPrevRelClientes.pas' {fPrevRelClientes},
  URelClientes in 'URelClientes.pas' {fRelClientes},
  UPrevFornecedores in 'UPrevFornecedores.pas' {fPrevFornecedores},
  URelFornecedores in 'URelFornecedores.pas' {fRelFornecedores},
  UPrevVendedores in 'UPrevVendedores.pas' {fPrevVendedores},
  URelVendedores in 'URelVendedores.pas' {fRelVendedores},
  USetor in 'USetor.pas' {fSetor},
  UCopiaPedidos in 'UCopiaPedidos.pas' {fCopiaPedidos},
  UEmissaoNotaFiscal in 'UEmissaoNotaFiscal.pas' {fEmissaoNotaFiscal},
  UPrevContas in 'UPrevContas.pas' {fPrevContas},
  URelContas in 'URelContas.pas' {fRelContas},
  URelCPagar in 'URelCPagar.pas' {fRelCPagar},
  UContasPagarPag in 'UContasPagarPag.pas' {fContasPagarPag},
  URelCReceber in 'URelCReceber.pas' {fRelCReceber},
  UBuscaPedido in 'UBuscaPedido.pas' {fBuscaPedido},
  UNotaEntrada in 'UNotaEntrada.pas' {fNotaEntrada},
  UConsNotaEnt in 'UConsNotaEnt.pas' {fConsNotaEnt},
  URelNotaEntrada in 'URelNotaEntrada.pas' {fRelNotaEntrada},
  USobre in 'USobre.pas' {fSobre},
  URelPagForn in 'URelPagForn.pas' {fRelPagForn},
  URelPgtoJuros in 'URelPgtoJuros.pas' {fRelPgtoJuros},
  URelRecCli in 'URelRecCli.pas' {fRelRecCli},
  UPrevRecCli in 'UPrevRecCli.pas' {fPrevRecCli},
  UPrevPgtoJuros in 'UPrevPgtoJuros.pas' {fPrevPgtoJuros},
  UPrevPagForn in 'UPrevPagForn.pas' {fPrevPagForn},
  UAlteraJuros in 'UAlteraJuros.pas' {fAlteraJuros},
  UBaixaItOC in 'UBaixaItOC.pas' {fBaixaItOC},
  UBaixaPedido in 'UBaixaPedido.pas' {fBaixaPedido},
  UBuscaOC in 'UBuscaOC.pas' {fBuscaOC},
  UConsCPagarHist in 'UConsCPagarHist.pas' {fConsCPagarHist},
  UConsCReceberHist in 'UConsCReceberHist.pas' {fConsCReceberHist},
  UConsPedido in 'UConsPedido.pas' {fConsPedido},
  UConsPedidoNota in 'UConsPedidoNota.pas' {fConsPedidoNota},
  UCPagarAltera in 'UCPagarAltera.pas' {fCPagarAltera},
  UCReceberAltera in 'UCReceberAltera.pas' {fCReceberAltera},
  UEntrExtOC in 'UEntrExtOC.pas' {fEntrExtOC},
  UEstPagamento in 'UEstPagamento.pas' {fEstPagamento},
  UEstPagamentoPagar in 'UEstPagamentoPagar.pas' {fEstPagamentoPagar},
  UEtiqCliente in 'UEtiqCliente.pas' {fEtiqCliente},
  UEtiqFornecedor in 'UEtiqFornecedor.pas' {fEtiqFornecedor},
  UEtiqVendedor in 'UEtiqVendedor.pas' {fEtiqVendedor},
  ULancComissao in 'ULancComissao.pas' {fLancComissao},
  UNotaEntradaGrade in 'UNotaEntradaGrade.pas' {fNotaEntradaGrade},
  UOpcaoPedido in 'UOpcaoPedido.pas' {fOpcaoPedido},
  UParametros in 'UParametros.pas' {fParametros},
  UPrevExtComissao2 in 'UPrevExtComissao2.pas' {fPrevExtComissao2},
  UPrevNComprasNatOpe in 'UPrevNComprasNatOpe.pas' {fPrevNComprasNatOpe},
  UPrevPedidosNaoFat in 'UPrevPedidosNaoFat.pas' {fPrevPedidosNaoFat},
  UPrevRelCPagar in 'UPrevRelCPagar.pas' {fPrevRelCPagar},
  UPrevRelCReceber in 'UPrevRelCReceber.pas' {fPrevRelCReceber},
  UPrevRelRotulos in 'UPrevRelRotulos.pas' {fPrevRelRotulos},
  UQuant in 'UQuant.pas' {fQuant},
  URegioes in 'URegioes.pas' {fRegioes},
  UObsAux in 'UObsAux.pas' {fObsAux},
  UUsuarios in 'UUsuarios.pas' {fUsuarios},
  ULogin in 'ULogin.pas' {fLogin},
  UAcesso in 'UAcesso.pas' {fAcesso},
  URelFichaTecnica in 'URelFichaTecnica.pas' {fRelFichaTecnica},
  UPrevCustoSetor in 'UPrevCustoSetor.pas' {fPrevCustoSetor},
  UConsHistMat in 'UConsHistMat.pas' {fConsHistMat},
  UPrevMatMinimo in 'UPrevMatMinimo.pas' {fPrevMatMinimo},
  URelMatMinimo in 'URelMatMinimo.pas' {fRelMatMinimo},
  UConsEstoqueMat in 'UConsEstoqueMat.pas' {fConsEstoqueMat},
  UPrevRelHistMaterial in 'UPrevRelHistMaterial.pas' {fPrevRelHistMaterial},
  UOpcaoTalao in 'UOpcaoTalao.pas' {fOpcaoTalao},
  UNotaFiscalGrade in 'UNotaFiscalGrade.pas' {fNotaFiscalGrade},
  UPrevNotaEntrada in 'UPrevNotaEntrada.pas' {fPrevNotaEntrada},
  UCopiaFornec in 'UCopiaFornec.pas' {fCopiaFornec},
  UPrevCalcMaterialLote in 'UPrevCalcMaterialLote.pas' {fPrevCalcMaterialLote},
  UConsOrdemCompra in 'UConsOrdemCompra.pas' {fConsOrdemCompra},
  UDctoEst in 'UDctoEst.pas' {fDctoEst},
  UDctoGrade in 'UDctoGrade.pas' {fDctoGrade},
  UConsDcto in 'UConsDcto.pas' {fConsDcto},
  URelRotulos in 'URelRotulos.pas' {fRelRotulos},
  UCopiaDuplicata in 'UCopiaDuplicata.pas' {fCopiaDuplicata},
  UPrevBalancoEst in 'UPrevBalancoEst.pas' {fPrevBalancoEst},
  UContasPagarDev in 'UContasPagarDev.pas' {fContasPagarDev},
  UConsLancCPagar in 'UConsLancCPagar.pas' {fConsLancCPagar},
  UPrevRelOC in 'UPrevRelOC.pas' {fPrevRelOC},
  UProdutoConsumo in 'UProdutoConsumo.pas' {fProdutoConsumo},
  URelCalcMaterial in 'URelCalcMaterial.pas' {FRelCalcMaterial},
  UFuncionario in 'UFuncionario.pas' {fFuncionario},
  URelTalao in 'URelTalao.pas' {fRelTalao},
  UPrevEmbDiario in 'UPrevEmbDiario.pas' {fPrevEmbDiario},
  URelEmbDiario in 'URelEmbDiario.pas' {fRelEmbDiario},
  UConsComissao in 'UConsComissao.pas' {fConsComissao},
  UPrevProgramacao in 'UPrevProgramacao.pas' {fPrevProgramacao},
  URelProgramacao in 'URelProgramacao.pas' {fRelProgramacao},
  UTabPreco in 'UTabPreco.pas' {fTabPreco},
  URelTabPreco in 'URelTabPreco.pas' {fRelTabPreco},
  UPrevContrFat in 'UPrevContrFat.pas' {fPrevContrFat},
  URelContrFat in 'URelContrFat.pas' {fRelContrFat},
  uRelCadCli in 'uRelCadCli.pas' {fRelCadCli},
  UHistPedido in 'UHistPedido.pas' {fHistPedido},
  URecPedido in 'URecPedido.pas' {fRecPedido},
  URelPedidosNaoFat in 'URelPedidosNaoFat.pas' {fRelPedidosNaoFat},
  URelExtComissao2 in 'URelExtComissao2.pas' {fRelExtComissao2},
  USenha in 'USenha.pas' {fSenha},
  UGeraSintegra in 'UGeraSintegra.pas' {fGeraSintegra},
  UCheques in 'UCheques.pas' {fCheques},
  UChequeComp in 'UChequeComp.pas' {fChequeComp},
  UDtReprog in 'UDtReprog.pas' {fDtReprog},
  UPrevContFornecedores in 'UPrevContFornecedores.pas' {fPrevContFornecedores},
  URelContFornecedores in 'URelContFornecedores.pas' {fRelContFornecedores},
  UGeraNotaEdi in 'UGeraNotaEdi.pas' {fGeraNotaEdi},
  URelOrdemCompraMail in 'URelOrdemCompraMail.pas' {fRelOrdemCompraMail},
  UConsOrcamento in 'UConsOrcamento.pas' {fConsOrcamento},
  UOrcamento in 'UOrcamento.pas' {fOrcamento},
  URelEstoque in 'URelEstoque.pas' {fRelEstoque},
  UPrevCReceberSem in 'UPrevCReceberSem.pas' {fPrevCReceberSem},
  UPrevCPagarSem in 'UPrevCPagarSem.pas' {fPrevCPagarSem},
  URelCPagarSem in 'URelCPagarSem.pas' {fRelCPagarSem},
  UNotaFiscalOC in 'UNotaFiscalOC.pas' {fNotaFiscalOC},
  UConsPedPendFat in 'UConsPedPendFat.pas' {fConsPedPendFat},
  URelOrcamentoMail in 'URelOrcamentoMail.pas' {fRelOrcamentoMail},
  UNotaFiscalItens in 'UNotaFiscalItens.pas' {fNotaFiscalItens},
  UTalao in 'UTalao.pas' {fTalao},
  UBaixaTalao in 'UBaixaTalao.pas' {fBaixaTalao},
  URecPedidoAzaleia in 'URecPedidoAzaleia.pas' {fRecPedidoAzaleia},
  UGeraNotaEdiAzaleia in 'UGeraNotaEdiAzaleia.pas' {fGeraNotaEdiAzaleia},
  UProjecaoEst in 'UProjecaoEst.pas' {fProjecaoEst},
  URelProjecaoEst in 'URelProjecaoEst.pas' {fRelProjecaoEst},
  UPrevBoletos in 'UPrevBoletos.pas' {fPrevBoletos},
  URelBoletos in 'URelBoletos.pas' {fRelBoletos},
  UValeItens in 'UValeItens.pas' {fValeItens},
  UVale in 'UVale.pas' {fVale},
  URelVale in 'URelVale.pas' {fRelVale},
  UConsVale in 'UConsVale.pas' {fConsVale},
  UPrevVale in 'UPrevVale.pas' {fPrevVale},
  URelVale2 in 'URelVale2.pas' {fRelVale2},
  UBuscaVale in 'UBuscaVale.pas' {fBuscaVale},
  uPrevProdMinimo in 'uPrevProdMinimo.pas' {fPrevProdMinimo},
  UConsPreco in 'UConsPreco.pas' {fConsPreco},
  UPedidoItemObs in 'UPedidoItemObs.pas' {fPedidoItemObs},
  SelfPrintDefs in 'SelfPrintDefs.pas',
  SendMail in 'SendMail.pas',
  SendMailOptions in 'SendMailOptions.pas' {FormSendMailOptions},
  UCartaCorrecao in 'UCartaCorrecao.pas' {fCartaCorrecao},
  URelCartaCorrecao in 'URelCartaCorrecao.pas' {fRelCartaCorrecao},
  UIrregularidade in 'UIrregularidade.pas' {fIrregularidade},
  UPrevVendasPeriodo in 'UPrevVendasPeriodo.pas' {fPrevVendasPeriodo},
  URelVendasPeriodo in 'URelVendasPeriodo.pas' {fRelVendasPeriodo},
  UCancelaTalao in 'UCancelaTalao.pas' {fCancelaTalao},
  UPrevTalaoMov in 'UPrevTalaoMov.pas' {fPrevTalaoMov},
  URelTalaoMov in 'URelTalaoMov.pas' {fRelTalaoMov},
  UTalaoHor in 'UTalaoHor.pas' {fTalaoHor},
  ULancaCPagar in 'ULancaCPagar.pas' {fLancaCPagar},
  UAltEstMinimo in 'UAltEstMinimo.pas' {fAltEstMinimo},
  UImpOC in 'UImpOC.pas' {fImpOC},
  UNFRetorno in 'UNFRetorno.pas' {fNFRetorno},
  URelCopiaCheque in 'URelCopiaCheque.pas' {fRelCopiaCheque},
  UConsHistCliente in 'UConsHistCliente.pas' {fConsHistCliente},
  URelHistCliente in 'URelHistCliente.pas' {fRelHistCliente},
  uConsHistClienteDet in 'uConsHistClienteDet.pas' {fConsHistClienteDet},
  UConsHistClienteProdCancelado in 'UConsHistClienteProdCancelado.pas' {fConsHistClienteProdCancelado},
  UPgtoComissao2 in 'UPgtoComissao2.pas' {fPgtoComissao2},
  URelRecibo in 'URelRecibo.pas' {fRelRecibo},
  UPrevPrevComissao in 'UPrevPrevComissao.pas' {fPrevPrevComissao},
  URelPrevComissao in 'URelPrevComissao.pas' {fRelPrevComissao},
  UPrevCliCompra in 'UPrevCliCompra.pas' {fPrevCliCompra},
  URelCliCompras in 'URelCliCompras.pas' {fRelCliCompras},
  UPrevCliNCompra in 'UPrevCliNCompra.pas' {fPrevCliNCompra},
  URelCliNCompra in 'URelCliNCompra.pas' {fRelCliNCompra},
  UProdutoTempo in 'UProdutoTempo.pas' {fProdutoTempo},
  UConsTalaoHor in 'UConsTalaoHor.pas' {fConsTalaoHor},
  UPrevHorasFuncionarios in 'UPrevHorasFuncionarios.pas' {fPrevHorasFuncionarios},
  URelHorasFuncionarios in 'URelHorasFuncionarios.pas' {fRelHorasFuncionarios},
  UPrevHorasProdutos in 'UPrevHorasProdutos.pas' {fPrevHorasProdutos},
  URelHorasProdutos in 'URelHorasProdutos.pas' {fRelHorasProdutos},
  UConsHorasProdutosDet in 'UConsHorasProdutosDet.pas' {fConsHorasProdutosDet},
  UConsHorasFuncionariosDet in 'UConsHorasFuncionariosDet.pas' {fConsHorasFuncionariosDet},
  UEscNotaDevolPorItem2 in 'UEscNotaDevolPorItem2.pas' {fEscNotaDevolPorItem2},
  UNotaFiscalNDevolvida in 'UNotaFiscalNDevolvida.pas' {fNotaFiscalNDevolvida},
  UConsNotaBeneficiamento in 'UConsNotaBeneficiamento.pas' {fConsNotaBeneficiamento},
  URelNotaBeneficiamento in 'URelNotaBeneficiamento.pas' {fRelNotaBeneficiamento},
  UConsNotaEntradaProd in 'UConsNotaEntradaProd.pas' {fConsNotaEntradaProd},
  UVerificaEstoque in 'UVerificaEstoque.pas' {fVerificaEstoque},
  URelVerifica in 'URelVerifica.pas' {fRelVerifica},
  UPrevAcumuladoFat in 'UPrevAcumuladoFat.pas' {fPrevAcumuladoFat},
  URelAcumuladoFat in 'URelAcumuladoFat.pas' {fRelAcumuladoFat},
  URelContrFatAcumulado in 'URelContrFatAcumulado.pas' {fRelContrFatAcumulado},
  UPrevPedCarteiraVlr in 'UPrevPedCarteiraVlr.pas' {fPrevPedCarteiraVlr},
  UPrevPedCarteira in 'UPrevPedCarteira.pas' {fPrevPedCarteira},
  URelPedCarteiraVlr in 'URelPedCarteiraVlr.pas' {fRelPedCarteiraVlr},
  URelPedCarteira in 'URelPedCarteira.pas' {fRelPedCarteira},
  UConsPedCarteiraDet in 'UConsPedCarteiraDet.pas' {fConsPedCarteiraDet},
  UPrevFichaFunc in 'UPrevFichaFunc.pas' {fPrevFichaFunc},
  URelFichaFunc in 'URelFichaFunc.pas' {fRelFichaFunc},
  UMotivo in 'UMotivo.pas' {fMotivo},
  UInfDtEntrega in 'UInfDtEntrega.pas' {fInfDtEntrega},
  UConsNotaVale in 'UConsNotaVale.pas' {fConsNotaVale},
  UEquipEpi in 'UEquipEpi.pas' {fEquipEpi},
  UConsEPI in 'UConsEPI.pas' {fConsEPI},
  URelNComprasNatOpe in 'URelNComprasNatOpe.pas' {fRelNComprasNatOpe},
  UConsMovAtelier in 'UConsMovAtelier.pas' {fConsMovAtelier},
  UMovAtelier in 'UMovAtelier.pas' {fMovAtelier},
  UBuscaTalao in 'UBuscaTalao.pas' {fBuscaTalao},
  uMovAtelierAlt in 'uMovAtelierAlt.pas' {fMovAtelierAlt},
  UbaixaMovAtelier in 'UbaixaMovAtelier.pas' {fBaixaMovAtelier},
  uConsMovAtelierDet in 'uConsMovAtelierDet.pas' {fConsMovAtelierDet},
  UVerificaCliente in 'UVerificaCliente.pas' {fVerificaCliente},
  UConsCPagarCReceber in 'UConsCPagarCReceber.pas' {fConsCPagarCReceber},
  URelCPagarCReceberDet in 'URelCPagarCReceberDet.pas' {fRelCPagarCReceberDet},
  URelCPagarCReceberRes in 'URelCPagarCReceberRes.pas' {fRelCPagarCReceberRes},
  UBaixaPedidoDet in 'UBaixaPedidoDet.pas' {fBaixaPedidoDet},
  USenhaControle in 'USenhaControle.pas' {fSenhaControle},
  UValeOC in 'UValeOC.pas' {fValeOC},
  UAprovaOrcamento in 'UAprovaOrcamento.pas' {fAprovaOrcamento},
  uPrevOrcamento in 'uPrevOrcamento.pas' {fPrevOrcamento},
  uRelOrcamento2 in 'uRelOrcamento2.pas' {fRelOrcamento2},
  UConsNotaFiscalBeneficiamento in 'UConsNotaFiscalBeneficiamento.pas' {fConsNotaFiscalBeneficiamento},
  URelNotaFiscalBeneficiamento in 'URelNotaFiscalBeneficiamento.pas' {fRelNotaFiscalBeneficiamento},
  UEscNotaFiscalDevolPorItem2 in 'UEscNotaFiscalDevolPorItem2.pas' {fEscNotaFiscalDevolPorItem2},
  UConsPedidoLog in 'UConsPedidoLog.pas' {fConsPedidoLog},
  UBaixaPedido2Det in 'UBaixaPedido2Det.pas' {fBaixaPedido2Det},
  UBaixaPedido2 in 'UBaixaPedido2.pas' {fBaixaPedido2},
  UHistGeral in 'UHistGeral.pas' {fHistGeral},
  URelHistGeralVend in 'URelHistGeralVend.pas' {fRelHistGeralVend},
  URelHistGeralCli in 'URelHistGeralCli.pas' {fRelHistGeralCli},
  URelHistGeralCliMes in 'URelHistGeralCliMes.pas' {fRelHistGeralCliMes},
  URelHistGeralCliProd in 'URelHistGeralCliProd.pas' {fRelHistGeralCliProd},
  URelHistGeralCliProdCor in 'URelHistGeralCliProdCor.pas' {fRelHistGeralCliProdCor},
  URelHistGeralCliProdMes in 'URelHistGeralCliProdMes.pas' {fRelHistGeralCliProdMes},
  URelHistGeralCliProdMesRes in 'URelHistGeralCliProdMesRes.pas' {fRelHistGeralCliProdMesRes},
  URelHistGeralProd in 'URelHistGeralProd.pas' {fRelHistGeralProd},
  URelHistGeralProdMes in 'URelHistGeralProdMes.pas' {fRelHistGeralProdMes},
  UConsEstUltMov in 'UConsEstUltMov.pas' {fConsEstUltMov},
  uConsCliente in 'uConsCliente.pas' {fConsCliente},
  UConsFornecedores in 'UConsFornecedores.pas' {fConsFornecedores},
  UPedidoItemCanc in 'UPedidoItemCanc.pas' {fPedidoItemCanc},
  UConsPedidoBR in 'UConsPedidoBR.pas' {fConsPedidoBR},
  URelPedidoBR in 'URelPedidoBR.pas' {fRelPedidoBR},
  URelPedidoBR2 in 'UrelPedidoBR2.pas' {fRelPedidoBR2},
  UConsPedidoBrMais in 'UConsPedidoBRmais.pas' {fConsPedidoBrMais},
  URelMateriaPrima in 'URelMateriaPrima.pas' {fRelMateriaPrima},
  UConsMateriaPrimaPed in 'UConsMateriaPrimaPed.pas' {fConsMateriaPrimaPed},
  UConsMateriaPrima in 'UConsMateriaPrima.pas' {fConsMateriaPrima},
  UBuscaDuplicata in 'UBuscaDuplicata.pas' {fBuscaDuplicata},
  UChequeCPagar in 'UChequeCPagar.pas' {fChequeCPagar},
  UContasPagar2 in 'UContasPagar2.pas' {fContasPagar2},
  UContasPagarPagSel in 'UContasPagarPagSel.pas' {fContasPagarPagSel},
  URelCPagar2 in 'URelCPagar2.pas' {fRelCPagar2},
  UCopiaConsCliente in 'UCopiaConsCliente.pas' {fCopiaConsCliente},
  URelClientes3 in 'URelClientes3.pas' {fRelClientes3},
  URelCopiaCheque3 in 'URelCopiaCheque3.pas' {fRelCopiaCheque3},
  LogTypes in '..\Logs\Src\LogTypes.pas',
  LogProvider in '..\Logs\Src\LogProvider.pas',
  arTypes in '..\rslib\arTypes.pas',
  rsDataSetError in '..\rslib\rsDataSetError.pas',
  URelTalao2 in 'URelTalao2.pas' {fRelTalao2},
  UBaixaProducaoItem in 'UBaixaProducaoItem.pas' {fBaixaProducaoItem},
  uIntegracao in 'FB\uIntegracao.pas',
  dmdCadProduto in 'FB\dmdCadProduto.pas' {dmCadProduto: TDataModule},
  dmdCadCliente in 'FB\dmdCadCliente.pas' {dmCadCliente: TDataModule},
  dmdCadCor in 'FB\dmdCadCor.pas' {dmCadCor: TDataModule},
  dmdCadFuncionario in 'FB\dmdCadFuncionario.pas' {dmCadFuncionario: TDataModule},
  DmdDatabase in 'FB\DmdDatabase.pas' {dmDatabase: TDataModule},
  dmdCadSetor in 'FB\dmdCadSetor.pas' {dmCadSetor: TDataModule},
  UCancelaTalaoFB in 'FB\UCancelaTalaoFB.pas' {fCancelaTalaoFB},
  UConsDefeito in 'FB\UConsDefeito.pas' {fConsDefeito},
  UParadas in 'FB\UParadas.pas' {fParadas},
  UConsParadas in 'FB\UConsParadas.pas' {fConsParadas},
  UDMTalao in 'FB\UDMTalao.pas' {DMTalao: TDataModule},
  UGerarTalao in 'FB\UGerarTalao.pas' {fGerarTalao},
  UConsPedidoPendLotes in 'UConsPedidoPendLotes.pas' {fConsPedidoPendLotes},
  UConsTalaoFB in 'FB\UConsTalaoFB.pas' {fConsTalaoFB},
  URelTalaoFB in 'FB\URelTalaoFB.pas' {fRelTalaoFB},
  UCopiaProduto in 'UCopiaProduto.pas' {fCopiaProduto},
  UConsTalaoFBDet in 'FB\UConsTalaoFBDet.pas' {FConsTalaoFBDet},
  dmdCadDefeitos in 'FB\dmdCadDefeitos.pas' {dmCadDefeitos: TDataModule},
  dmdCadParadas in 'FB\dmdCadParadas.pas' {dmCadParadas: TDataModule},
  UDefeito in 'FB\UDefeito.pas' {fDefeito},
  UConsSetorMov in 'FB\UConsSetorMov.pas' {fConsSetorMov},
  UBaixaProducaoTed in 'UBaixaProducaoTed.pas' {fBaixaProducaoTed},
  UHorarioProd in 'FB\UHorarioProd.pas' {fHorarioProd},
  UDMHorarioProd in 'FB\UDMHorarioProd.pas' {DMHorarioProd: TDataModule},
  UBaixaProducao2 in 'FB\UBaixaProducao2.pas' {fBaixaProducao2},
  UBaixaProducaoMov in 'FB\UBaixaProducaoMov.pas' {fBaixaProducaoMov},
  UBaixaProducaoPC in 'FB\UBaixaProducaoPC.pas' {fBaixaProducaoPC},
  URelListagemSetor in 'URelListagemSetor.pas' {fRelListagemSetor},
  URelListagemParadas in 'URelListagemParadas.pas' {fRelListagemParadas},
  URelListagemDefeito in 'URelListagemDefeito.pas' {fRelListagemDefeito},
  UDMSetorTempo in 'FB\UDMSetorTempo.pas' {DMSetorTempo: TDataModule},
  URelMenuBaixaProdTed in 'URelMenuBaixaProdTed.pas' {fRelMenuBaixaProdTed},
  UCidade in '..\generico\Manutencao\UCidade.pas' {fCidade},
  UPais in '..\generico\Manutencao\UPais.pas' {fPais},
  UCSTIPI in '..\generico\Manutencao\UCSTIPI.pas' {fCSTIPI},
  UDMNotaFiscal in 'UDMNotaFiscal.pas' {DMNotaFiscal: TDataModule},
  UNFeDados in 'UNFeDados.pas',
  uNFe in '..\generico\faturamento\uNFe.pas' {fNFe},
  nfe_v110 in '..\generico\faturamento\nfe_v110.pas',
  uNFeComandos in '..\generico\faturamento\uNFeComandos.pas',
  URelDanfe in '..\generico\faturamento\URelDANFE.pas' {fRelDANFE},
  UGeracoes in '..\generico\faturamento\UGeracoes.pas',
  UEscFilial in '..\generico\Manutencao\UEscFilial.pas' {fEscFilial},
  UFilial in '..\generico\Manutencao\UFilial.pas' {fFilial},
  UNotaFiscalCancelada in '..\generico\faturamento\UNotaFiscalCancelada.pas' {fNotaFiscalCancelada},
  UConsNotaFiscal in 'UConsNotaFiscal.pas' {fConsNotaFiscal},
  UPrevNotasNatOpe2 in '..\generico\faturamento\UPrevNotasNatOpe2.pas' {fPrevNotasNatOpe2},
  URelNatNota2 in '..\generico\faturamento\URelNatNota2.pas' {fRelNatNota2},
  UContasReceber2 in '..\generico\CReceber\UContasReceber2.pas' {fContasReceber2},
  UContasReceberPagSel in '..\generico\CReceber\UContasReceberPagSel.pas' {fContasReceberPagSel},
  UContasReceberDev in '..\generico\CReceber\UContasReceberDev.pas' {fContasReceberDev},
  UContasReceberPag in '..\generico\CReceber\UContasReceberPag.pas' {fContasReceberPag},
  UConsCReceber in '..\generico\CReceber\UConsCReceber.pas' {fConsCReceber},
  URelCReceber3 in '..\generico\CReceber\URelCReceber3.pas' {fRelCReceber3},
  URelCReceber2 in '..\generico\CReceber\URelCReceber2.pas' {fRelCReceber2},
  URelCopiaDupl in '..\generico\CReceber\URelCopiaDupl.pas' {fRelCopiaDupl},
  URelRegDuplicatas in '..\generico\CReceber\URelRegDuplicatas.pas' {fRelRegDuplicatas},
  ULancaCReceber in '..\generico\CReceber\ULancaCReceber.pas' {fLancaCReceber},
  ULancaCReceberItens in '..\generico\CReceber\ULancaCReceberItens.pas' {fLancaCReceberItens},
  URelCReceberSem in '..\generico\CReceber\URelCReceberSem.pas' {fRelCReceberSem},
  UConsLancCReceber in '..\generico\CReceber\UConsLancCReceber.pas' {fConsLancCReceber},
  UNotaFiscalConfirma in '..\generico\faturamento\UNotaFiscalConfirma.pas' {fNotaFiscalConfirma},
  UPrevDuplicatas in '..\generico\CReceber\UPrevDuplicatas.pas' {fPrevDuplicatas},
  URelDuplicata in '..\generico\CReceber\URelDuplicata.pas' {fRelDuplicata},
  UUf in '..\generico\Manutencao\UUf.pas' {fUf},
  UNotaFiscalOutrasDespesas in '..\generico\faturamento\UNotaFiscalOutrasDespesas.pas' {fNotaFiscalOutrasDespesas},
  UInfDescontoNota in '..\generico\faturamento\UInfDescontoNota.pas' {fInfDescontoNota},
  uConsFuncionarioTalao in 'uConsFuncionarioTalao.pas' {fConsFuncionarioTalao},
  uConsFuncionarioTempo in 'uConsFuncionarioTempo.pas' {fConsFuncionarioTempo},
  URelCReceberCliRed in '..\generico\creceber\URelCReceberCliRed.pas' {fRelCReceberCliRed},
  UConsTalaoSetor in 'UConsTalaoSetor.pas' {fConsTalaoSetor},
  UConsFuncionarioMov in 'FB\UConsFuncionarioMov.pas' {fConsFuncionarioMov},
  UConsFuncionarioMovHist in 'FB\UConsFuncionarioMovHist.pas' {fConsFuncionarioMovHist},
  uConsQuebrasMov in 'uConsQuebrasMov.pas' {fConsQuebrasMov},
  UConsProdutividade in 'FB\UConsProdutividade.pas' {fConsProdutividade},
  URelCReceberTipoCobrRed in '..\generico\CReceber\URelCReceberTipoCobrRed.pas' {fRelCReceberTipoCobrRed},
  URelCReceberTipoCobr in '..\generico\CReceber\URelCReceberTipoCobr.pas' {fRelCReceberTipoCobr},
  UOutrosServicosNota in '..\generico\faturamento\UOutrosServicosNota.pas' {fOutrosServicosNota},
  UOrigemProd in '..\generico\faturamento\UOrigemProd.pas' {fOrigemProd},
  UDMTabImposto in '..\generico\faturamento\UDMTabImposto.pas' {DMTabImposto: TDataModule},
  UNotaFiscalAliq in '..\generico\faturamento\UNotaFiscalAliq.pas' {fNotaFiscalAliq},
  uCalculos in '..\generico\faturamento\uCalculos.pas',
  UDMNFe in '..\generico\faturamento\UDMNFe.pas' {DMNFe: TDataModule},
  UNotaFiscalReboque in '..\generico\faturamento\UNotaFiscalReboque.pas' {fNotaFiscalReboque},
  UNotaFiscalLacre in '..\generico\faturamento\UNotaFiscalLacre.pas' {fNotaFiscalLacre},
  UNotaFiscalContingencia in '..\generico\faturamento\UNotaFiscalContingencia.pas' {fNotaFiscalContingencia},
  UClasFiscal in '..\generico\manutencao\UClasFiscal.pas' {fClasFiscal},
  UNatOperacao in '..\generico\manutencao\UNatOperacao.pas' {fNatOperacao},
  USitTributaria in '..\generico\manutencao\USitTributaria.pas' {fSitTributaria},
  UTabCofins in '..\generico\faturamento\UTabCofins.pas' {fTabCofins},
  UTabPis in '..\generico\faturamento\UTabPis.pas' {fTabPis},
  UNFeInutilizacao in '..\generico\faturamento\UNFeInutilizacao.pas' {fNFeInutilizacao},
  USitTributariaSimples in '..\generico\manutencao\USitTributariaSimples.pas' {fSitTributariaSimples},
  UPercSimples in '..\generico\faturamento\UPercSimples.pas' {fPercSimples},
  URegimeTrib in '..\generico\faturamento\URegimeTrib.pas' {fRegimeTrib},
  UTransp in '..\generico\manutencao\UTransp.pas' {fTransp},
  UCopiaCli in '..\generico\manutencao\UCopiaCli.pas' {fCopiaCli},
  URelNatOper in '..\generico\manutencao\URelNatOper.pas' {fRelNatOper},
  uNotaFiscalAjustarIcms in '..\generico\faturamento\uNotaFiscalAjustarIcms.pas' {fNotaFiscalAjustarIcms},
  UNotaFiscalOBS in '..\generico\faturamento\UNotaFiscalOBS.pas' {fNotaFiscalOBS},
  UMovimentos2 in '..\generico\financeiro\UMovimentos2.pas' {fMovimentos2},
  UMovimentosEnc in '..\generico\financeiro\UMovimentosEnc.pas' {fMovimentosEnc},
  uMovimentosIns in '..\generico\financeiro\uMovimentosIns.pas' {fMovimentosIns},
  UFluxoFuturo in '..\generico\financeiro\UFluxoFuturo.pas' {fFluxoFuturo},
  UContasBoletoManual in '..\generico\financeiro\UContasBoletoManual.pas' {fContasBoletoManual},
  URelMovimento in '..\generico\financeiro\URelMovimento.pas' {fRelMovimento},
  UConsSaldos in '..\generico\financeiro\UConsSaldos.pas' {fConsSaldos},
  UConsFinanceiro in '..\generico\financeiro\UConsFinanceiro.pas' {fConsFinanceiro},
  UConsMovFinanceiro in '..\generico\financeiro\UConsMovFinanceiro.pas' {fConsMovFinanceiro},
  URelFinanceiro in '..\generico\financeiro\URelFinanceiro.pas' {fRelFinanceiro},
  URelFluxoFuturo in '..\generico\financeiro\URelFluxoFuturo.pas' {fRelFluxoFuturo},
  URelSaldos in '..\generico\financeiro\URelSaldos.pas' {fRelSaldos},
  UPrevCheque in '..\generico\financeiro\UPrevCheque.pas' {fPrevCheque},
  URelCheque in '..\generico\financeiro\URelCheque.pas' {fRelCheque},
  UJuros in '..\generico\financeiro\UJuros.pas' {fJuros},
  UPlanoContas in '..\generico\financeiro\UPlanoContas.pas' {fPlanoContas},
  UFeriado in '..\generico\manutencao\UFeriado.pas' {fFeriado},
  UAtividade in '..\generico\manutencao\UAtividade.pas' {fAtividade},
  UCor in '..\generico\manutencao\UCor.pas' {fCor},
  UOutros in '..\generico\manutencao\UOutros.pas' {fOutros},
  UAgeContato in '..\generico\manutencao\UAgeContato.pas' {fAgeContato},
  UConsAgeContato in '..\generico\manutencao\UConsAgeContato.pas' {fConsAgeContato},
  UConsFornecAtiv in '..\generico\manutencao\UConsFornecAtiv.pas' {fConsFornecAtiv},
  UCondPgto in '..\generico\manutencao\UCondPgto.pas' {fCondPgto},
  UAgendaTelef in '..\generico\manutencao\UAgendaTelef.pas' {fAgendaTelef},
  UHistorico in '..\generico\manutencao\UHistorico.pas' {fHistorico},
  UGrupoCliente in '..\generico\manutencao\UGrupoCliente.pas' {fGrupoCliente},
  UImpressora in '..\generico\manutencao\UImpressora.pas' {fImpressora},
  UIndexador in '..\generico\faturamento\UIndexador.pas' {fIndexador},
  UPermissoes in '..\generico\manutencao\UPermissoes.pas' {fPermissoes},
  UTipoCobranca in '..\generico\creceber\UTipoCobranca.pas' {fTipoCobranca},
  UAtualizaDtVencto2 in '..\generico\creceber\UAtualizaDtVencto2.pas' {fAtualizaDtVencto2},
  UAutorizacao in '..\generico\manutencao\UAutorizacao.pas' {fAutorizacao},
  UEscImpressora in '..\generico\manutencao\UEscImpressora.pas' {fEscImpressora},
  UVerificarPedVale in 'UVerificarPedVale.pas' {fVerificarPedVale},
  UConsContasPagar in 'UConsContasPagar.pas' {fConsContasPagar},
  URelCPagarPagto in 'URelCPagarPagto.pas' {fRelCPagarPagto},
  URelCPagarPagtoForn in 'URelCPagarPagtoForn.pas' {fRelCPagarPagtoForn},
  UConsPlanoContasCad in '..\generico\financeiro\UConsPlanoContasCad.pas' {fConsPlanoContasCad},
  URelPlanoContasCad in '..\generico\financeiro\URelPlanoContasCad.pas' {fRelPlanoContasCad},
  UVerificaContasRecPag in 'UVerificaContasRecPag.pas' {fVerificaContasRecPag},
  UVoltaNotaFIscal in 'UVoltaNotaFiscal.pas' {fVoltaNotaFiscal},
  UCReceberAlteraSel in '..\generico\creceber\UCReceberAlteraSel.pas' {fCReceberAlteraSel},
  UContas in 'UContas.pas' {fContas},
  URelReciboRec2 in 'URelReciboRec2.pas' {fRelReciboRec2},
  UConsNotaCancelada in '..\ssbasico\UConsNotaCancelada.pas' {fConsNotaCancelada},
  URelNotaCancelada in '..\generico\faturamento\URelNotaCancelada.pas' {fRelNotaCancelada},
  UDMNFeFB in '..\generico\faturamento\UDMNFeFB.pas' {DMNFeFB: TDataModule},
  UNotaFiscalCCe in '..\generico\faturamento\UNotaFiscalCCe.pas' {fNotaFiscalCCe},
  UNotaFiscalCCeDet in '..\generico\faturamento\UNotaFiscalCCeDet.pas' {fNotaFiscalCCeDet},
  URelCCe in '..\generico\faturamento\URelCCe.pas' {fRelCCe},
  UNFeEmailC in '..\generico\faturamento\UNFeEmailC.pas' {fNFeEmailC},
  UNFeEmail in '..\generico\faturamento\UNFeEmail.pas' {fNFeEmail},
  UConsMovAux in '..\generico\financeiro\UConsMovAux.pas' {fConsMovAux},
  uTalaoCRapida in 'uTalaoCRapida.pas' {fTalaoCRapida},
  UConsPedidoTalao in 'UConsPedidoTalao.pas' {fConsPedidoTalao},
  URelPedidoTalao in 'URelPedidoTalao.pas' {fRelPedidoTalao},
  UDM2 in 'UDM2.pas' {DM2: TDataModule},
  UDMTabIBPT in '..\generico\faturamento\UDMTabIBPT.pas' {DMTabIBPT: TDataModule},
  UTabIBPTC in '..\generico\faturamento\UTabIBPTC.pas' {fTabIBPTC},
  UTabIBPT in '..\generico\faturamento\UTabIBPT.pas' {fTabIBPT},
  uUtil_NFe in '..\generico\faturamento\uUtil_NFe.pas',
  rsDBUtils in '..\rslib\nova\rsDBUtils.pas',
  uUtil in 'uUtil.pas',
  URelTalao_Branco in 'URelTalao_Branco.pas' {fRelTalao_Branco},
  UDMConsNotaEletronica in '..\generico\NFe\UDMConsNotaEletronica.pas' {DMConsNotaEletronica: TDataModule},
  DmdDatabase_NFeBD in '..\generico\NFe\DmdDatabase_NFeBD.pas' {dmDatabase_NFeBD: TDataModule},
  uNFeConsts in '..\NFe 3.10\NFESrv\uNFeConsts.pas',
  enviNFe_v310 in '..\generico\NFe\enviNFe_v310.pas',
  uXMLNFe3_10 in '..\generico\NFe\uXMLNFe3_10.pas',
  dmdNFeConfig in '..\generico\NFe\dmdNFeConfig.pas' {DMNFeConfig: TDataModule},
  UNotaFiscalRef in '..\generico\faturamento\UNotaFiscalRef.pas' {fNotaFiscalRef},
  URelCliente2 in 'URelCliente2.pas' {fRelCliente2},
  UDMTabEnqIPI in '..\generico\faturamento\UDMTabEnqIPI.pas' {DMTabEnqIPI: TDataModule},
  UTabEnqIPIC in '..\generico\faturamento\UTabEnqIPIC.pas' {fTabEnqIPIC},
  UTabEnqIPI in '..\generico\faturamento\UTabEnqIPI.pas' {fTabEnqIPI},
  USel_EnqIPI in '..\generico\faturamento\USel_EnqIPI.pas' {fSel_EnqIPI},
  uUtilPadrao in 'uUtilPadrao.pas',
  enviNFe_v400 in '..\generico\NFe\4.00\enviNFe_v400.pas',
  uXMLNFe4_00 in '..\generico\NFe\4.00\uXMLNFe4_00.pas';

{$R *.RES}

begin
  Application.Initialize;
  Session.AddPassword('46w3zq');
  Application.Title := 'NK';
  Application.CreateForm(TdmDatabase, dmDatabase);
  Application.CreateForm(TDM1, DM1);
  Application.CreateForm(TDM2, DM2);
  Application.CreateForm(TfMenuP, fMenuP);
  //Application.CreateForm(Tclose, close);
  Application.CreateForm(TfMenuP, fMenuP);
  Application.Run;
end.

