unit URelCartaCorrecao;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Qrctrls, QuickRpt, ExtCtrls, RLReport;

type
  TfRelCartaCorrecao = class(TForm)
    QuickRep1: TQuickRep;
    PageHeaderBand1: TQRBand;
    QRShape1: TQRShape;
    QRLabel1: TQRLabel;
    QRShape2: TQRShape;
    QRShape3: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRLabel2: TQRLabel;
    QRDBText1: TQRDBText;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRShape9: TQRShape;
    QRShape8: TQRShape;
    QRShape7: TQRShape;
    QRShape10: TQRShape;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRLabel7: TQRLabel;
    QRShape24: TQRShape;
    QRLabel8: TQRLabel;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape30: TQRShape;
    QRShape31: TQRShape;
    QRShape32: TQRShape;
    QRShape33: TQRShape;
    QRShape34: TQRShape;
    QRShape35: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape38: TQRShape;
    QRShape39: TQRShape;
    QRShape40: TQRShape;
    QRCod1: TQRLabel;
    QRCod2: TQRLabel;
    QRCod4: TQRLabel;
    QRCod3: TQRLabel;
    QRCod5: TQRLabel;
    QRCod6: TQRLabel;
    QRCod7: TQRLabel;
    QRCod8: TQRLabel;
    QRCod9: TQRLabel;
    QRCod10: TQRLabel;
    QRCod11: TQRLabel;
    QRCod16: TQRLabel;
    QRCod15: TQRLabel;
    QRCod14: TQRLabel;
    QRCod13: TQRLabel;
    QRCod12: TQRLabel;
    QRShape41: TQRShape;
    QRNome1: TQRLabel;
    QRNome2: TQRLabel;
    QRNome4: TQRLabel;
    QRNome7: TQRLabel;
    QRNome6: TQRLabel;
    QRNome5: TQRLabel;
    QRNome13: TQRLabel;
    QRNome12: TQRLabel;
    QRNome11: TQRLabel;
    QRNome10: TQRLabel;
    QRNome9: TQRLabel;
    QRNome8: TQRLabel;
    QRNome16: TQRLabel;
    QRNome3: TQRLabel;
    QRNome15: TQRLabel;
    QRNome14: TQRLabel;
    QRShape42: TQRShape;
    QRShape43: TQRShape;
    QRShape44: TQRShape;
    QRShape45: TQRShape;
    QRShape46: TQRShape;
    QRShape47: TQRShape;
    QRShape48: TQRShape;
    QRShape49: TQRShape;
    QRShape50: TQRShape;
    QRShape51: TQRShape;
    QRShape52: TQRShape;
    QRShape53: TQRShape;
    QRShape54: TQRShape;
    QRShape55: TQRShape;
    QRShape56: TQRShape;
    QRShape57: TQRShape;
    QRShape58: TQRShape;
    QRLabel41: TQRLabel;
    QRShape59: TQRShape;
    QRLabel42: TQRLabel;
    QRShape60: TQRShape;
    QRShape61: TQRShape;
    QRShape62: TQRShape;
    QRShape63: TQRShape;
    QRShape64: TQRShape;
    QRShape65: TQRShape;
    QRShape66: TQRShape;
    QRShape67: TQRShape;
    QRShape68: TQRShape;
    QRShape69: TQRShape;
    QRShape70: TQRShape;
    QRShape71: TQRShape;
    QRShape72: TQRShape;
    QRShape73: TQRShape;
    QRShape74: TQRShape;
    QRShape75: TQRShape;
    QRCod17: TQRLabel;
    QRCod18: TQRLabel;
    QRCod20: TQRLabel;
    QRCod19: TQRLabel;
    QRCod21: TQRLabel;
    QRCod22: TQRLabel;
    QRCod23: TQRLabel;
    QRCod24: TQRLabel;
    QRCod25: TQRLabel;
    QRCod26: TQRLabel;
    QRCod27: TQRLabel;
    QRCod32: TQRLabel;
    QRCod31: TQRLabel;
    QRCod30: TQRLabel;
    QRCod29: TQRLabel;
    QRCod28: TQRLabel;
    QRShape76: TQRShape;
    QRNome17: TQRLabel;
    QRNome18: TQRLabel;
    QRNome20: TQRLabel;
    QRNome23: TQRLabel;
    QRNome22: TQRLabel;
    QRNome21: TQRLabel;
    QRNome29: TQRLabel;
    QRNome28: TQRLabel;
    QRNome27: TQRLabel;
    QRNome26: TQRLabel;
    QRNome25: TQRLabel;
    QRNome24: TQRLabel;
    QRNome32: TQRLabel;
    QRNome19: TQRLabel;
    QRNome31: TQRLabel;
    QRNome30: TQRLabel;
    QRShape77: TQRShape;
    QRShape78: TQRShape;
    QRShape79: TQRShape;
    QRShape80: TQRShape;
    QRShape81: TQRShape;
    QRShape82: TQRShape;
    QRShape83: TQRShape;
    QRShape84: TQRShape;
    QRShape85: TQRShape;
    QRShape86: TQRShape;
    QRShape87: TQRShape;
    QRShape88: TQRShape;
    QRShape89: TQRShape;
    QRShape90: TQRShape;
    QRShape91: TQRShape;
    QRShape92: TQRShape;
    QRShape93: TQRShape;
    QRLabel75: TQRLabel;
    QRShape94: TQRShape;
    QRLabel76: TQRLabel;
    QRShape95: TQRShape;
    QRShape96: TQRShape;
    QRShape97: TQRShape;
    QRShape98: TQRShape;
    QRShape99: TQRShape;
    QRShape100: TQRShape;
    QRShape101: TQRShape;
    QRShape102: TQRShape;
    QRShape103: TQRShape;
    QRShape104: TQRShape;
    QRShape105: TQRShape;
    QRShape106: TQRShape;
    QRShape107: TQRShape;
    QRShape108: TQRShape;
    QRShape109: TQRShape;
    QRShape110: TQRShape;
    QRCod33: TQRLabel;
    QRCod34: TQRLabel;
    QRCod36: TQRLabel;
    QRCod35: TQRLabel;
    QRCod37: TQRLabel;
    QRCod38: TQRLabel;
    QRCod39: TQRLabel;
    QRCod40: TQRLabel;
    QRCod41: TQRLabel;
    QRCod42: TQRLabel;
    QRCod43: TQRLabel;
    QRCod48: TQRLabel;
    QRCod47: TQRLabel;
    QRCod46: TQRLabel;
    QRCod45: TQRLabel;
    QRCod44: TQRLabel;
    QRShape111: TQRShape;
    QRNome33: TQRLabel;
    QRNome34: TQRLabel;
    QRNome36: TQRLabel;
    QRNome39: TQRLabel;
    QRNome38: TQRLabel;
    QRNome35: TQRLabel;
    DetailBand1: TQRBand;
    PageFooterBand1: TQRBand;
    QRLabel101: TQRLabel;
    QRLabel102: TQRLabel;
    QRLabel103: TQRLabel;
    QRLabel104: TQRLabel;
    QRShape116: TQRShape;
    QRLabel105: TQRLabel;
    QRShape117: TQRShape;
    QRLabel107: TQRLabel;
    QRLabel108: TQRLabel;
    QRDBText2: TQRDBText;
    QRSubDetail1: TQRSubDetail;
    QRLabel109: TQRLabel;
    QRShape118: TQRShape;
    QRShape119: TQRShape;
    QRLabel110: TQRLabel;
    QRLabel111: TQRLabel;
    QRDBText3: TQRDBText;
    QRDBText4: TQRDBText;
    QRDBText5: TQRDBText;
    QRDBText6: TQRDBText;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    QRLabel112: TQRLabel;
    QRShape112: TQRShape;
    QRLabel113: TQRLabel;
    QRShape115: TQRShape;
    QRShape113: TQRShape;
    QRDBText10: TQRDBText;
    QRNome40: TQRLabel;
    QRNome37: TQRLabel;
    QRNome41: TQRLabel;
    QRNome42: TQRLabel;
    QRNome43: TQRLabel;
    QRNome44: TQRLabel;
    QRNome45: TQRLabel;
    QRNome46: TQRLabel;
    QRNome47: TQRLabel;
    QRNome48: TQRLabel;
    RLReport1: TRLReport;
    RLBand2: TRLBand;
    RLLabel115: TRLLabel;
    RLLabel116: TRLLabel;
    RLLabel117: TRLLabel;
    RLLabel118: TRLLabel;
    RLDraw113: TRLDraw;
    RLLabel119: TRLLabel;
    RLDraw114: TRLDraw;
    RLLabel120: TRLLabel;
    RLDraw115: TRLDraw;
    RLLabel121: TRLLabel;
    RLLabel122: TRLLabel;
    RLDraw116: TRLDraw;
    RLLabel123: TRLLabel;
    RLSubDetail1: TRLSubDetail;
    RLBand1: TRLBand;
    RLDraw2: TRLDraw;
    RLDraw1: TRLDraw;
    RLLabel1: TRLLabel;
    RLLabel2: TRLLabel;
    RLDBText3: TRLDBText;
    RLDBText1: TRLDBText;
    RLDBText2: TRLDBText;
    RLDBText5: TRLDBText;
    RLDBText4: TRLDBText;
    RLDBText6: TRLDBText;
    RLDBText7: TRLDBText;
    RLDraw4: TRLDraw;
    RLDraw3: TRLDraw;
    RLDraw5: TRLDraw;
    RLDraw6: TRLDraw;
    RLDBText8: TRLDBText;
    RLDBText9: TRLDBText;
    RLLabel4: TRLLabel;
    RLLabel5: TRLLabel;
    RLLabel6: TRLLabel;
    RLLabel7: TRLLabel;
    RLLabel8: TRLLabel;
    RLDraw7: TRLDraw;
    RLDraw8: TRLDraw;
    RLDraw9: TRLDraw;
    RLDraw10: TRLDraw;
    RLDraw11: TRLDraw;
    RLDraw12: TRLDraw;
    RLDraw13: TRLDraw;
    RLDraw14: TRLDraw;
    RLDraw15: TRLDraw;
    RLDraw16: TRLDraw;
    RLDraw17: TRLDraw;
    RLDraw18: TRLDraw;
    RLDraw19: TRLDraw;
    RLDraw20: TRLDraw;
    RLDraw21: TRLDraw;
    RLDraw22: TRLDraw;
    RLDraw23: TRLDraw;
    RLDraw24: TRLDraw;
    RLDraw25: TRLDraw;
    RLDraw26: TRLDraw;
    RLDraw27: TRLDraw;
    RLDraw28: TRLDraw;
    RLDraw29: TRLDraw;
    RLDraw30: TRLDraw;
    RLDraw31: TRLDraw;
    RLDraw32: TRLDraw;
    RLDraw33: TRLDraw;
    RLDraw34: TRLDraw;
    RLDraw35: TRLDraw;
    RLDraw36: TRLDraw;
    RLDraw37: TRLDraw;
    RLDraw38: TRLDraw;
    RLDraw39: TRLDraw;
    RLDraw40: TRLDraw;
    RLDraw58: TRLDraw;
    RLDraw59: TRLDraw;
    RLDraw60: TRLDraw;
    RLDraw61: TRLDraw;
    RLDraw62: TRLDraw;
    RLDraw63: TRLDraw;
    RLDraw64: TRLDraw;
    RLDraw65: TRLDraw;
    RLDraw66: TRLDraw;
    RLDraw67: TRLDraw;
    RLDraw68: TRLDraw;
    RLDraw69: TRLDraw;
    RLDraw70: TRLDraw;
    RLDraw71: TRLDraw;
    RLDraw72: TRLDraw;
    RLDraw73: TRLDraw;
    RLDraw74: TRLDraw;
    RLDraw75: TRLDraw;
    RLLabel9: TRLLabel;
    RLCod1: TRLLabel;
    RLCod2: TRLLabel;
    RLCod3: TRLLabel;
    RLCod4: TRLLabel;
    RLCod5: TRLLabel;
    RLCod6: TRLLabel;
    RLCod7: TRLLabel;
    RLCod8: TRLLabel;
    RLCod9: TRLLabel;
    RLCod10: TRLLabel;
    RLCod11: TRLLabel;
    RLCod12: TRLLabel;
    RLCod13: TRLLabel;
    RLCod14: TRLLabel;
    RLCod15: TRLLabel;
    RLCod16: TRLLabel;
    RLNome1: TRLLabel;
    RLNome2: TRLLabel;
    RLNome3: TRLLabel;
    RLNome4: TRLLabel;
    RLNome5: TRLLabel;
    RLNome6: TRLLabel;
    RLNome7: TRLLabel;
    RLNome8: TRLLabel;
    RLNome9: TRLLabel;
    RLNome10: TRLLabel;
    RLNome11: TRLLabel;
    RLNome12: TRLLabel;
    RLNome13: TRLLabel;
    RLNome14: TRLLabel;
    RLNome15: TRLLabel;
    RLNome16: TRLLabel;
    RLLabel42: TRLLabel;
    RLLabel44: TRLLabel;
    RLDraw76: TRLDraw;
    RLDraw77: TRLDraw;
    RLDraw78: TRLDraw;
    RLDraw79: TRLDraw;
    RLDraw80: TRLDraw;
    RLDraw81: TRLDraw;
    RLDraw82: TRLDraw;
    RLDraw83: TRLDraw;
    RLDraw84: TRLDraw;
    RLDraw85: TRLDraw;
    RLDraw86: TRLDraw;
    RLDraw87: TRLDraw;
    RLDraw88: TRLDraw;
    RLDraw89: TRLDraw;
    RLDraw90: TRLDraw;
    RLDraw91: TRLDraw;
    RLDraw92: TRLDraw;
    RLDraw93: TRLDraw;
    RLLabel45: TRLLabel;
    RLCod17: TRLLabel;
    RLCod18: TRLLabel;
    RLCod19: TRLLabel;
    RLCod20: TRLLabel;
    RLCod21: TRLLabel;
    RLCod22: TRLLabel;
    RLCod23: TRLLabel;
    RLCod24: TRLLabel;
    RLCod25: TRLLabel;
    RLCod26: TRLLabel;
    RLCod27: TRLLabel;
    RLCod28: TRLLabel;
    RLCod29: TRLLabel;
    RLCod30: TRLLabel;
    RLCod31: TRLLabel;
    RLCod32: TRLLabel;
    RLNome17: TRLLabel;
    RLNome18: TRLLabel;
    RLNome21: TRLLabel;
    RLNome19: TRLLabel;
    RLNome20: TRLLabel;
    RLNome22: TRLLabel;
    RLNome23: TRLLabel;
    RLNome24: TRLLabel;
    RLNome25: TRLLabel;
    RLNome26: TRLLabel;
    RLNome27: TRLLabel;
    RLNome28: TRLLabel;
    RLNome29: TRLLabel;
    RLNome30: TRLLabel;
    RLNome31: TRLLabel;
    RLNome32: TRLLabel;
    RLDraw94: TRLDraw;
    RLDraw95: TRLDraw;
    RLDraw41: TRLDraw;
    RLDraw42: TRLDraw;
    RLDraw43: TRLDraw;
    RLDraw44: TRLDraw;
    RLDraw45: TRLDraw;
    RLDraw46: TRLDraw;
    RLDraw47: TRLDraw;
    RLDraw48: TRLDraw;
    RLDraw49: TRLDraw;
    RLDraw50: TRLDraw;
    RLDraw51: TRLDraw;
    RLDraw52: TRLDraw;
    RLDraw53: TRLDraw;
    RLDraw54: TRLDraw;
    RLDraw55: TRLDraw;
    RLDraw56: TRLDraw;
    RLDraw117: TRLDraw;
    RLLabel124: TRLLabel;
    RLLabel125: TRLLabel;
    RLDraw118: TRLDraw;
    RLDraw119: TRLDraw;
    RLDraw120: TRLDraw;
    RLDraw121: TRLDraw;
    RLDraw122: TRLDraw;
    RLDraw123: TRLDraw;
    RLDraw124: TRLDraw;
    RLDraw125: TRLDraw;
    RLDraw126: TRLDraw;
    RLDraw127: TRLDraw;
    RLDraw128: TRLDraw;
    RLDraw129: TRLDraw;
    RLDraw130: TRLDraw;
    RLDraw131: TRLDraw;
    RLDraw132: TRLDraw;
    RLDraw133: TRLDraw;
    RLCod33: TRLLabel;
    RLCod34: TRLLabel;
    RLCod35: TRLLabel;
    RLCod36: TRLLabel;
    RLCod37: TRLLabel;
    RLCod38: TRLLabel;
    RLCod39: TRLLabel;
    RLCod40: TRLLabel;
    RLCod41: TRLLabel;
    RLCod42: TRLLabel;
    RLCod43: TRLLabel;
    RLCod44: TRLLabel;
    RLCod45: TRLLabel;
    RLCod46: TRLLabel;
    RLCod47: TRLLabel;
    RLCod48: TRLLabel;
    RLNome33: TRLLabel;
    RLNome34: TRLLabel;
    RLNome35: TRLLabel;
    RLNome36: TRLLabel;
    RLNome37: TRLLabel;
    RLNome39: TRLLabel;
    RLNome42: TRLLabel;
    RLNome43: TRLLabel;
    RLNome44: TRLLabel;
    RLNome45: TRLLabel;
    RLNome46: TRLLabel;
    RLNome47: TRLLabel;
    RLNome48: TRLLabel;
    RLNome38: TRLLabel;
    RLNome41: TRLLabel;
    RLNome40: TRLLabel;
    RLBand3: TRLBand;
    RLDBText11: TRLDBText;
    RLLabel112: TRLLabel;
    RLDraw112: TRLDraw;
    RLDBMemo1: TRLDBMemo;
    RLLabel3: TRLLabel;
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure PageHeaderBand1BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);
    procedure RLBand1BeforePrint(Sender: TObject; var PrintIt: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fRelCartaCorrecao: TfRelCartaCorrecao;

implementation

uses UDM1;

{$R *.DFM}

procedure TfRelCartaCorrecao.FormClose(Sender: TObject;
  var Action: TCloseAction);
begin
  Action := Cafree;
end;

procedure TfRelCartaCorrecao.PageHeaderBand1BeforePrint(
  Sender: TQRCustomBand; var PrintBand: Boolean);
var
  i : Integer;
begin
  i := 0;
  DM1.tIrregularidade.IndexFieldNames := 'Codigo';
  DM1.tIrregularidade.First;
  while not DM1.tIrregularidade.Eof do
    begin
      inc(i);
      if i > 48 then
        ShowMessage('Existe mais de 48 irregularidades cadastradas!')
      else
        begin
          TQRLabel(FindComponent('QRCod'+IntToStr(i))).Caption  := DM1.tIrregularidadeCodigo.AsString;
          TQRLabel(FindComponent('QRNome'+IntToStr(i))).Caption := DM1.tIrregularidadeNome.AsString;
        end;
      DM1.tIrregularidade.Next;
    end;
  inc(i);
  while i < 49 do
    begin
      TQRLabel(FindComponent('QRNome'+IntToStr(i))).Caption := '';
      inc(i);
    end;
end;

procedure TfRelCartaCorrecao.RLBand1BeforePrint(Sender: TObject;
  var PrintIt: Boolean);
var i: Integer;
begin

 i := 0;
  DM1.tIrregularidade.IndexFieldNames := 'Codigo';
  DM1.tIrregularidade.First;
  while not DM1.tIrregularidade.Eof do
    begin
      inc(i);
      if i > 48 then
        ShowMessage('Existe mais de 48 irregularidades cadastradas!')
      else
        begin
          TRLLabel(FindComponent('RLCod'+IntToStr(i))).Caption  := DM1.tIrregularidadeCodigo.AsString;
          TRLLabel(FindComponent('RLNome'+IntToStr(i))).Caption := DM1.tIrregularidadeNome.AsString;
        end;
      DM1.tIrregularidade.Next;
    end;
  inc(i);
  while i < 49 do
    begin
      TRLLabel(FindComponent('RLNome'+IntToStr(i))).Caption := '';
      inc(i);
    end;
end;

end.
