unit URelTalao_Branco;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ExtCtrls, QuickRpt, Qrctrls, DB, DBTables;

type
  TfRelTalao_Branco = class(TForm)
    QuickRep1: TQuickRep;
    DetailBand1: TQRBand;
    QRDBText1: TQRDBText;
    QRLabel2: TQRLabel;
    QRDBText3: TQRDBText;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRDBText4: TQRDBText;
    QRLabel6: TQRLabel;
    QRShape3: TQRShape;
    QRLabel9: TQRLabel;
    QRDBText2: TQRDBText;
    QRLabel1: TQRLabel;
    QRDBText5: TQRDBText;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRLabel5: TQRLabel;
    QRShape4: TQRShape;
    QRLabel7: TQRLabel;
    QRShape5: TQRShape;
    QRLabel8: TQRLabel;
    QRShape6: TQRShape;
    QRLabel10: TQRLabel;
    QRShape7: TQRShape;
    QRLabel11: TQRLabel;
    QRShape8: TQRShape;
    QRLabel12: TQRLabel;
    QRShape9: TQRShape;
    QRLabel13: TQRLabel;
    QRShape10: TQRShape;
    QRLabel14: TQRLabel;
    QRShape11: TQRShape;
    QRLabel15: TQRLabel;
    QRShape12: TQRShape;
    QRLabel16: TQRLabel;
    QRShape13: TQRShape;
    QRShape14: TQRShape;
    QRShape15: TQRShape;
    QRShape16: TQRShape;
    QRShape17: TQRShape;
    QRShape18: TQRShape;
    QRShape19: TQRShape;
    QRShape20: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRShape23: TQRShape;
    QRShape24: TQRShape;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRShape27: TQRShape;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape30: TQRShape;
    QRShape31: TQRShape;
    QRShape32: TQRShape;
    QRShape33: TQRShape;
    QRShape34: TQRShape;
    QRShape35: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRShape38: TQRShape;
    QRShape39: TQRShape;
    QRShape40: TQRShape;
    QRShape41: TQRShape;
    QRShape42: TQRShape;
    QRShape43: TQRShape;
    QRShape44: TQRShape;
    QRShape45: TQRShape;
    QRShape46: TQRShape;
    QRShape47: TQRShape;
    QRShape48: TQRShape;
    QRShape49: TQRShape;
    QRShape50: TQRShape;
    QRShape51: TQRShape;
    QRShape52: TQRShape;
    QRShape53: TQRShape;
    QRShape54: TQRShape;
    QRShape55: TQRShape;
    QRShape56: TQRShape;
    QRShape57: TQRShape;
    QRShape58: TQRShape;
    QRShape59: TQRShape;
    QRShape60: TQRShape;
    QRShape61: TQRShape;
    QRShape62: TQRShape;
    QRShape63: TQRShape;
    QRShape64: TQRShape;
    QRShape65: TQRShape;
    QRShape66: TQRShape;
    QRShape67: TQRShape;
    QRShape68: TQRShape;
    QRShape69: TQRShape;
    QRShape70: TQRShape;
    QRShape71: TQRShape;
    QRShape72: TQRShape;
    QRShape73: TQRShape;
    QRShape74: TQRShape;
    QRShape75: TQRShape;
    QRShape76: TQRShape;
    QRShape77: TQRShape;
    QRShape78: TQRShape;
    QRShape79: TQRShape;
    QRShape80: TQRShape;
    QRShape81: TQRShape;
    QRShape82: TQRShape;
    QRShape83: TQRShape;
    QRShape84: TQRShape;
    QRShape85: TQRShape;
    QRShape86: TQRShape;
    QRShape87: TQRShape;
    QRShape88: TQRShape;
    QRShape89: TQRShape;
    QRShape90: TQRShape;
    QRShape91: TQRShape;
    QRShape92: TQRShape;
    QRShape93: TQRShape;
    QRShape94: TQRShape;
    QRShape95: TQRShape;
    QRShape96: TQRShape;
    QRShape97: TQRShape;
    QRShape98: TQRShape;
    QRShape99: TQRShape;
    QRShape100: TQRShape;
    QRShape101: TQRShape;
    QRShape102: TQRShape;
    QRShape103: TQRShape;
    QRShape104: TQRShape;
    QRShape105: TQRShape;
    QRShape106: TQRShape;
    QRShape107: TQRShape;
    QRShape108: TQRShape;
    QRShape109: TQRShape;
    QRShape110: TQRShape;
    QRShape111: TQRShape;
    QRShape112: TQRShape;
    QRShape113: TQRShape;
    QRShape114: TQRShape;
    QRShape115: TQRShape;
    QRShape116: TQRShape;
    QRShape117: TQRShape;
    QRShape118: TQRShape;
    QRShape119: TQRShape;
    QRShape120: TQRShape;
    QRShape121: TQRShape;
    QRShape122: TQRShape;
    QRShape123: TQRShape;
    QRShape124: TQRShape;
    QRShape125: TQRShape;
    QRShape126: TQRShape;
    QRShape127: TQRShape;
    QRShape128: TQRShape;
    QRShape129: TQRShape;
    QRShape130: TQRShape;
    QRShape131: TQRShape;
    QRShape132: TQRShape;
    QRShape133: TQRShape;
    QRSetor1: TQRLabel;
    QRShape134: TQRShape;
    QRShape135: TQRShape;
    QRShape136: TQRShape;
    QRSetor2: TQRLabel;
    QRShape137: TQRShape;
    QRShape138: TQRShape;
    QRSetor3: TQRLabel;
    QRShape139: TQRShape;
    QRSetor5: TQRLabel;
    QRShape140: TQRShape;
    QRShape141: TQRShape;
    QRShape142: TQRShape;
    QRSetor6: TQRLabel;
    QRShape143: TQRShape;
    QRShape144: TQRShape;
    QRSetor7: TQRLabel;
    QRShape145: TQRShape;
    QRSetor9: TQRLabel;
    QRShape146: TQRShape;
    QRShape147: TQRShape;
    QRShape148: TQRShape;
    QRSetor10: TQRLabel;
    QRShape149: TQRShape;
    QRShape150: TQRShape;
    QRSetor11: TQRLabel;
    QRShape151: TQRShape;
    QRShape152: TQRShape;
    QRShape153: TQRShape;
    QRShape154: TQRShape;
    QRShape155: TQRShape;
    QRShape156: TQRShape;
    QRShape157: TQRShape;
    QRShape158: TQRShape;
    QRShape159: TQRShape;
    QRShape160: TQRShape;
    QRShape161: TQRShape;
    QRShape162: TQRShape;
    QRShape163: TQRShape;
    QRSetor4: TQRLabel;
    QRShape164: TQRShape;
    QRShape165: TQRShape;
    QRSetor8: TQRLabel;
    QRShape166: TQRShape;
    QRShape167: TQRShape;
    QRSetor12: TQRLabel;
    QRLabel17: TQRLabel;
    QRDBText6: TQRDBText;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRDBText7: TQRDBText;
    QRShape168: TQRShape;
    QRDBText8: TQRDBText;
    QRLabel20: TQRLabel;
    QRDBText9: TQRDBText;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRDBText10: TQRDBText;
    QRLabel23: TQRLabel;
    QRLabel24: TQRLabel;
    QRDBText11: TQRDBText;
    QRLabel25: TQRLabel;
    QRDBText12: TQRDBText;
    QRShape169: TQRShape;
    QRShape170: TQRShape;
    QRLabel26: TQRLabel;
    QRShape171: TQRShape;
    QRLabel27: TQRLabel;
    QRShape172: TQRShape;
    QRLabel28: TQRLabel;
    QRShape173: TQRShape;
    QRLabel29: TQRLabel;
    QRShape174: TQRShape;
    QRLabel30: TQRLabel;
    QRShape175: TQRShape;
    QRLabel31: TQRLabel;
    QRShape176: TQRShape;
    QRLabel32: TQRLabel;
    QRShape177: TQRShape;
    QRLabel33: TQRLabel;
    QRShape178: TQRShape;
    QRLabel34: TQRLabel;
    QRShape179: TQRShape;
    QRLabel35: TQRLabel;
    QRShape180: TQRShape;
    QRShape181: TQRShape;
    QRShape182: TQRShape;
    QRShape183: TQRShape;
    QRShape184: TQRShape;
    QRShape185: TQRShape;
    QRShape186: TQRShape;
    QRShape187: TQRShape;
    QRShape188: TQRShape;
    QRShape189: TQRShape;
    QRShape190: TQRShape;
    QRShape191: TQRShape;
    QRShape192: TQRShape;
    QRShape193: TQRShape;
    QRShape194: TQRShape;
    QRShape195: TQRShape;
    QRShape196: TQRShape;
    QRShape197: TQRShape;
    QRShape198: TQRShape;
    QRShape199: TQRShape;
    QRShape200: TQRShape;
    QRShape201: TQRShape;
    QRShape202: TQRShape;
    QRShape203: TQRShape;
    QRShape204: TQRShape;
    QRShape205: TQRShape;
    QRShape206: TQRShape;
    QRShape207: TQRShape;
    QRShape208: TQRShape;
    QRShape209: TQRShape;
    QRShape210: TQRShape;
    QRShape211: TQRShape;
    QRShape212: TQRShape;
    QRShape213: TQRShape;
    QRShape214: TQRShape;
    QRShape215: TQRShape;
    QRShape216: TQRShape;
    QRShape217: TQRShape;
    QRShape218: TQRShape;
    QRShape219: TQRShape;
    QRShape220: TQRShape;
    QRShape221: TQRShape;
    QRShape222: TQRShape;
    QRShape223: TQRShape;
    QRShape224: TQRShape;
    QRShape225: TQRShape;
    QRShape226: TQRShape;
    QRShape227: TQRShape;
    QRShape228: TQRShape;
    QRShape229: TQRShape;
    QRShape230: TQRShape;
    QRShape231: TQRShape;
    QRShape232: TQRShape;
    QRShape233: TQRShape;
    QRShape234: TQRShape;
    QRShape235: TQRShape;
    QRShape236: TQRShape;
    QRShape237: TQRShape;
    QRShape238: TQRShape;
    QRShape239: TQRShape;
    QRShape240: TQRShape;
    QRShape241: TQRShape;
    QRShape242: TQRShape;
    QRShape243: TQRShape;
    QRShape244: TQRShape;
    QRShape245: TQRShape;
    QRShape246: TQRShape;
    QRShape247: TQRShape;
    QRShape248: TQRShape;
    QRShape249: TQRShape;
    QRShape250: TQRShape;
    QRShape251: TQRShape;
    QRShape252: TQRShape;
    QRShape253: TQRShape;
    QRShape254: TQRShape;
    QRShape255: TQRShape;
    QRShape256: TQRShape;
    QRShape257: TQRShape;
    QRShape258: TQRShape;
    QRShape259: TQRShape;
    QRShape260: TQRShape;
    QRShape261: TQRShape;
    QRShape262: TQRShape;
    QRShape263: TQRShape;
    QRShape264: TQRShape;
    QRShape265: TQRShape;
    QRShape266: TQRShape;
    QRShape267: TQRShape;
    QRShape268: TQRShape;
    QRShape269: TQRShape;
    QRShape270: TQRShape;
    QRShape271: TQRShape;
    QRShape272: TQRShape;
    QRShape273: TQRShape;
    QRShape274: TQRShape;
    QRShape275: TQRShape;
    QRShape276: TQRShape;
    QRShape277: TQRShape;
    QRShape278: TQRShape;
    QRShape279: TQRShape;
    QRShape280: TQRShape;
    QRShape281: TQRShape;
    QRShape282: TQRShape;
    QRShape283: TQRShape;
    QRShape284: TQRShape;
    QRShape285: TQRShape;
    QRShape286: TQRShape;
    QRShape287: TQRShape;
    QRShape288: TQRShape;
    QRShape289: TQRShape;
    QRShape290: TQRShape;
    QRShape291: TQRShape;
    QRShape292: TQRShape;
    QRShape293: TQRShape;
    QRShape294: TQRShape;
    QRShape295: TQRShape;
    QRShape296: TQRShape;
    QRShape297: TQRShape;
    QRShape298: TQRShape;
    QRShape299: TQRShape;
    QRShape300: TQRShape;
    QRLabel36: TQRLabel;
    QRShape301: TQRShape;
    QRShape302: TQRShape;
    QRShape303: TQRShape;
    QRLabel37: TQRLabel;
    QRShape304: TQRShape;
    QRShape305: TQRShape;
    QRLabel38: TQRLabel;
    QRShape306: TQRShape;
    QRLabel39: TQRLabel;
    QRShape307: TQRShape;
    QRShape308: TQRShape;
    QRShape309: TQRShape;
    QRLabel40: TQRLabel;
    QRShape310: TQRShape;
    QRShape311: TQRShape;
    QRLabel41: TQRLabel;
    QRShape312: TQRShape;
    QRLabel42: TQRLabel;
    QRShape313: TQRShape;
    QRShape314: TQRShape;
    QRShape315: TQRShape;
    QRLabel43: TQRLabel;
    QRShape316: TQRShape;
    QRShape317: TQRShape;
    QRLabel44: TQRLabel;
    QRShape318: TQRShape;
    QRShape319: TQRShape;
    QRShape320: TQRShape;
    QRShape321: TQRShape;
    QRShape322: TQRShape;
    QRShape323: TQRShape;
    QRShape324: TQRShape;
    QRShape325: TQRShape;
    QRShape326: TQRShape;
    QRShape327: TQRShape;
    QRShape328: TQRShape;
    QRShape329: TQRShape;
    QRLabel45: TQRLabel;
    QRShape330: TQRShape;
    QRShape331: TQRShape;
    QRLabel46: TQRLabel;
    QRShape332: TQRShape;
    QRShape333: TQRShape;
    QRLabel47: TQRLabel;
    QRLabel48: TQRLabel;
    QRDBText13: TQRDBText;
    QRLabel49: TQRLabel;
    QRLabel50: TQRLabel;
    QRDBText14: TQRDBText;
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure DetailBand1BeforePrint(Sender: TQRCustomBand;
      var PrintBand: Boolean);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  fRelTalao_Branco: TfRelTalao_Branco;

implementation

uses UDM1, UTalao;

{$R *.DFM}

procedure TfRelTalao_Branco.FormClose(Sender: TObject; var Action: TCloseAction);
begin
  Action := Cafree;
end;

procedure TfRelTalao_Branco.DetailBand1BeforePrint(Sender: TQRCustomBand;
  var PrintBand: Boolean);
//var
//  i : integer;  
begin
  {QRLabel9.Caption := DM1.tTalaolkReferencia.AsString + ' - ' + DM1.tTalaolkDescMaterial.AsString + ' - ' + DM1.tTalaolkNomeProduto.AsString + DM1.tTalaolkNomeCor.AsString;
  for i := 1 to 12 do
    TQRLabel(FindComponent('QRSetor'+IntToStr(i))).Caption := '';
  i := 0;
  DM1.tSetor.First;
  while not DM1.tSetor.Eof do
    begin
      inc(i);
      if i > 12 then
        DM1.tSetor.Last
      else
      if DM1.tSetorImpTalao.AsBoolean then
        TQRLabel(FindComponent('QRSetor'+IntToStr(i))).Caption := DM1.tSetorNome.AsString;
      DM1.tSetor.Next;
    end;}
end;

end.
